name: Build GNB

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y liblzo2-dev liblz4-dev
          
      - name: Show build.sh content
        run: cat build.sh
          
      - name: Build with debug mode
        run: |
          chmod +x build.sh
          bash -x ./build.sh
          
      - name: Verify build output
        run: |
          echo "构建目录内容:"
          ls -l build/
          echo "文件类型:"
          file build/*
          
      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gnb-binaries
          path: build/
          retention-days: 1
