name: Build GNB UDP over TCP

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y liblzo2-dev liblz4-dev build-essential
          
      - name: Compile for Linux
        run: make -f Makefile.linux
        
      - name: Archive Linux binary
        uses: actions/upload-artifact@v4
        with:
          name: gnb-udp-over-tcp-linux
          path: gnb_udp_over_tcp
          retention-days: 3

  build-windows:
    needs: build-linux  # 可移除以实现并行构建
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install MinGW dependencies
        run: sudo apt-get update && sudo apt-get install -y mingw-w64
          
      - name: Compile for Windows
        run: make -f Makefile.mingw_x86_64
        
      - name: Archive Windows executable
        uses: actions/upload-artifact@v4
        with:
          name: gnb-udp-over-tcp-windows
          path: gnb_udp_over_tcp.exe
          retention-days: 3
