name: Build GNB UDP over TCP (Windows)

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y mingw-w64
      - run: make -f Makefile.mingw_x86_64 CC=x86_64-w64-mingw32-gcc
      - uses: actions/upload-artifact@v4
        with:
          name: gnb_udp_over_tcp-windows
          path: gnb_udp_over_tcp.exe
