name: Build GNB UDP over TCP

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y liblzo2-dev liblz4-dev build-essential
      - run: |
          make -f Makefile.linux
          mkdir -p build
          mv gnb_udp_over_tcp build/
      - uses: actions/upload-artifact@v4
        with:
          name: gnb-binary
          path: build/gnb_udp_over_tcp
