name: Build GNB UDP over TCP

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake

      - name: Create build directory
        run: mkdir -p build

      - name: Configure with CMake
        working-directory: build
        run: cmake ..

      - name: Compile project
        working-directory: build
        run: make

      - name: Verify binary
        run: |
          if [ -f "build/gnb_udp_over_tcp" ]; then
            echo "✅ 编译成功！"
            file build/gnb_udp_over_tcp
          else
            echo "❌ 错误：可执行文件未生成"
            ls -lR build/
            exit 1
          fi

      - name: Archive binary
        uses: actions/upload-artifact@v4
        with:
          name: gnb_bin
          path: build/gnb_udp_over_tcp
          retention-days: 1
