name: Build GNB

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y liblzo2-dev liblz4-dev gcc make
          
      - name: Try official Makefile
        run: |
          # 尝试使用官方 Makefile
          if [ -f "Makefile.linux" ]; then
            echo "使用 Makefile.linux 编译..."
            make -f Makefile.linux
          else
            echo "错误: Makefile.linux 不存在"
            exit 1
          fi
          
      - name: Move artifacts to build directory
        run: |
          mkdir -p build
          # 尝试移动所有可能的目标文件
          [ -f "gnb" ] && mv gnb build/
          [ -f "gnb_ctl" ] && mv gnb_ctl build/
          [ -f "gnb_crypto" ] && mv gnb_crypto build/
          
      - name: Verify build output
        run: |
          if [ -d "build" ] && [ -n "$(ls -A build)" ]; then
            echo "✅ 编译成功!"
            echo "构建目录内容:"
            ls -l build/
          else
            echo "❌ 错误: 编译失败或没有生成文件"
            echo "尝试手动编译..."
            exit 1
          fi
          
      - name: Archive build artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: gnb-binaries
          path: build/
          retention-days: 1
