name: Build GNB

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y liblzo2-dev liblz4-dev build-essential
          
      - name: Setup lwip dependency
        run: |
          echo "设置 lwip 依赖..."
          mkdir -p libs
          cd libs
          wget https://github.com/gnbdev/lwip/archive/refs/heads/master.tar.gz
          tar xzf master.tar.gz
          mv lwip-master lwip
          rm master.tar.gz
          cd ..
          
      - name: Verify directory structure
        run: |
          echo "项目结构:"
          tree -L 3 || ls -R
          
      - name: Show Makefile content
        run: |
          echo "Makefile.linux 内容:"
          cat Makefile.linux
          
      - name: Compile for Linux
        run: |
          echo "开始编译..."
          make -f Makefile.linux
          
          echo "编译结果:"
          ls -l gnb gnb_ctl gnb_crypto || true
          
          echo "创建 build 目录..."
          mkdir -p build
          mv gnb gnb_ctl gnb_crypto build/ 2>/dev/null || true
          
      - name: Verify build output
        run: |
          if [ -d "build" ]; then
            echo "构建目录内容:"
            ls -l build/
            echo "文件详情:"
            file build/*
          else
            echo "错误: build 目录不存在"
            echo "当前目录内容:"
            ls -la
            exit 1
          fi
          
      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gnb-binaries
          path: build/
          retention-days: 1
