name: Build GNB UDP over TCP

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y liblzo2-dev liblz4-dev build-essential
          
      - name: Compile for Linux
        run: make -f Makefile.linux
        
      - name: Verify compilation
        run: |
          echo "编译后目录内容:"
          ls -la
          
          # 检查可执行文件是否存在
          for bin in gnb gnb_ctl gnb_crypto; do
            if [ -f "$bin" ]; then
              echo "✅ $bin 在根目录"
            elif [ -f "src/$bin" ]; then
              echo "✅ $bin 在 src 目录"
            else
              echo "❌ 未找到 $bin"
            fi
          done
          
      - name: Prepare build directory
        run: |
          mkdir -p build
          
          # 搜索并移动所有可能的二进制文件
          find . -type f \( -name "gnb" -o -name "gnb_ctl" -o -name "gnb_crypto" \) \
                 -not -path "./build/*" \
                 -exec mv -v {} build/ \;
          
          echo "构建目录内容:"
          ls -l build/
          if [ -z "$(ls -A build)" ]; then
            echo "❌ 错误: 未找到任何可执行文件"
            echo "所有文件:"
            find . -type f -exec ls -l {} \;
            exit 1
          fi
          
      - name: Archive binaries
        uses: actions/upload-artifact@v4
        with:
          name: gnb-binaries
          path: build/
          if-no-files-found: error
          retention-days: 1
